# Generated by Django 4.1.3 on 2023-09-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewSpeedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.IntegerField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('newSpeed', models.IntegerField(max_length=50)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
