# Generated by Django 4.1.3 on 2023-09-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspeedrequest',
            name='accountNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newspeedrequest',
            name='newSpeed',
            field=models.IntegerField(),
        ),
    ]
