# Generated by Django 4.1.3 on 2023-10-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0002_alter_newspeedrequest_accountnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspeedrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='newspeedrequest',
            name='newSpeed',
        ),
        migrations.RemoveField(
            model_name='newspeedrequest',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='newspeedrequest',
            name='MRC',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='newspeedrequest',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newspeedrequest',
            name='customerType',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newspeedrequest',
            name='nodeID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='newspeedrequest',
            name='productOffer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newspeedrequest',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newspeedrequest',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newspeedrequest',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
