# Generated by Django 4.1.3 on 2023-10-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0003_remove_newspeedrequest_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspeedrequest',
            name='accountNumber',
            field=models.CharField(max_length=20),
        ),
    ]
