# Generated by Django 4.1.3 on 2023-10-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0004_alter_newspeedrequest_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspeedrequest',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newspeedrequest',
            name='customerType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newspeedrequest',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newspeedrequest',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newspeedrequest',
            name='productOffer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newspeedrequest',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
