# Generated by Django 4.1.3 on 2023-10-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0006_rename_name_newspeedrequest_customername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspeedrequest',
            old_name='MRC',
            new_name='newMRC',
        ),
        migrations.AlterField(
            model_name='newspeedrequest',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newspeedrequest',
            name='email',
            field=models.TextField(),
        ),
    ]
