# Generated by Django 4.1.3 on 2023-10-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0008_rename_status_newspeedrequest_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspeedrequest',
            name='productOffer',
        ),
        migrations.AddField(
            model_name='newspeedrequest',
            name='currentPlan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newspeedrequest',
            name='customerType',
            field=models.TextField(null=True),
        ),
    ]
