# Generated by Django 4.1.3 on 2023-10-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0009_remove_newspeedrequest_productoffer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspeedrequest',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
