# Generated by Django 4.1.3 on 2023-10-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0010_alter_newspeedrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspeedrequest',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
